name: Deploy gaurav-strapi-task8 to ECS

on:
  push:
    branches:
      - main   # Runs when you push to main branch

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: gaurav-strapi-task8-repo
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    #################################################
    # STEP 1 - CHECKOUT CODE
    #################################################
    - name: Checkout Code
      uses: actions/checkout@v3

    #################################################
    # STEP 2 - CONFIGURE AWS CREDENTIALS
    #################################################
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    #################################################
    # STEP 3 - LOGIN TO ECR
    #################################################
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    #################################################
    # STEP 4 - BUILD & PUSH DOCKER IMAGE
    #################################################
    - name: Build and Push Docker Image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
        docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    #################################################
    # STEP 5 - TERRAFORM INIT
    #################################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    #################################################
    # STEP 6 - TERRAFORM APPLY
    #################################################
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve